name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Fix Project Format
        run: |
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' StikDebug.xcodeproj/project.pbxproj
          sed -i '' 's/preferredProjectObjectVersion = 77/preferredProjectObjectVersion = 56/' StikDebug.xcodeproj/project.pbxproj

      - name: Archive Build (Unsigned)
        run: |
          xcodebuild clean archive \
            -project StikDebug.xcodeproj \
            -scheme "StikDebug" \
            -configuration Release \
            -archivePath build/StikDebug.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_OPTIMIZATION_LEVEL="-Onone" \
            IPHONEOS_DEPLOYMENT_TARGET=17.4

      - name: Create IPA from Archive
        run: |
          # Copy the .app from the archive
          cp -R build/StikDebug.xcarchive/Products/Applications/StikDebug.app .

          # Package the app into an IPA
          mkdir -p Payload
          cp -R StikDebug.app Payload/
          zip -r StikDebug.ipa Payload
          rm -rf Payload StikDebug.app

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: StikDebug.ipa
          path: StikDebug.ipa
          retention-days: 90 
